sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs
before_install:
  - npm i -g npm@^4.4.0
before_script:
  - npm prune
script:
  - npm run test:single
after_success: # Will not run if tests fail
#   - npm run semantic-release
